
include: package:flutter_lints/flutter.yaml
linter:
  rules:
    prefer_const_declarations: false
    directives_ordering: false
    avoid_print: false
    always_put_required_named_parameters_first: false
